version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
configuration: Release

skip_commits:
  files:
  - docs/*
  - README.md

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
- dotnet restore

after_build:
- dotnet pack

build:
  publish_nuget: true
  verbosity: normal