version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
configuration: Release

skip_commits:
  files:
  - '**/*.md'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

before_build:
- choco install rabbitmq --ignoredependencies -y
- dotnet restore

after_build:
- dotnet pack

build_script:
- cmd: dotnet build HealthRabbitMQ.sln

test_script:
- cmd: dotnet test tests/App.Metrics.Health.Checks.RabbitMQ.Tests