version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
configuration: Release

skip_commits:
  files:
  - '**/*.md'

install:
- ps: >-
    choco install rabbitmq -Version 3.6.14

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

before_build:
- dotnet restore

after_build:
- dotnet pack

build_script:
- cmd: dotnet build HealthRabbitMQ.sln

test_script:
- cmd: dotnet test tests/App.Metrics.Health.Checks.RabbitMQ.Tests