version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
configuration: Release

skip_commits:
  files:
  - '**/*.md'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

before_build:
- choco install rabbitmq --ignoredependencies -y
- dotnet restore

after_build:
- dotnet pack --include-symbols --configuration %CONFIGURATION% --no-build --output ..\..\nupkgs /p:PackageVersion=%APPVEYOR_BUILD_VERSION%

artifacts:
- path: nupkgs/*.nupkg

build_script:
- cmd: dotnet build --configuration %CONFIGURATION%

test_script:
- cmd: dotnet test tests/App.Metrics.Health.Checks.RabbitMQ.Tests

deploy:
  provider: NuGet
  api_key:
    secure: zENvH3gbuZCsYxkF3LVve2nDsR8lfcYsdEUshfED6zrmV5i87aF/sdofSiVWPmMC
  skip_symbols: false
  artifacts: /.*\.nupkg/